---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: attendee-service_source

outputs:
- name: package-output

run:
  path: attendee-service_source/ci/tasks/package.sh

